# Generated by Django 4.2.11 on 2024-05-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="douban_id",
            field=models.CharField(default="无", max_length=100),
        ),
    ]
