# Generated by Django 4.2.11 on 2024-05-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_douban_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="discription",
            field=models.TextField(),
        ),
    ]
