# Generated by Django 4.2.11 on 2024-05-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_movie_discription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="discription",
        ),
    ]
