# Generated by Django 4.2.11 on 2024-05-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_movie_discription"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="cover_image_blob",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
