# Generated by Django 4.2.11 on 2024-05-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_movie_cover_image_blob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="cover_image_blob",
        ),
    ]
